"""added quantity, instruction, and tag models as well as changes to recipe and all related tables

Revision ID: 0ff335ec09f1
Revises: d19c056f9592
Create Date: 2024-07-16 14:29:41.527908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff335ec09f1'
down_revision: Union[str, None] = 'd19c056f9592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instructions', 'recipes', ['recipe_id'], ['id'])
    op.alter_column('recipes', 'rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'rating',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'instructions', type_='foreignkey')
    op.drop_column('instructions', 'recipe_id')
    # ### end Alembic commands ###
